config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "boxes#index"
  resources :boxes, only: %i[index edit destroy update create] do
    resources :connects, only: %i[index destroy create] do
      collection do
        delete 'destroy_all'
        get 'search'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
class Box < ApplicationRecord
  def attributes
    { id: nil, name: nil }
  end

  def destroy_all_history
    connects.each do |connect|
      new_history = Deletehistory.new
      new_history.user_id = connect.user_id
      new_history.title = connect.title
      new_history.link = connect.link

      if Deletehistory.find_by(link: new_history.link)
        old_history = Deletehistory.find_by(link: new_history.link)
        old_history.destroy
      end
      new_history.save
      histories_stock_limit = 20
      histories = Deletehistory.all
      histories[0].destroy if histories.count > histories_stock_limit
    end
  end

  validates :name, :position, presence: true

  belongs_to :user
  has_many :connects, dependent: :destroy
end

app/models/connect.rb
class Connect < ApplicationRecord
  validates :title, :link, :position, presence: true
  belongs_to :user
  belongs_to :box

  def delete_history
    new_history = Deletehistory.new
    new_history.user_id = user_id
    new_history.title = title
    new_history.link = link

    if Deletehistory.find_by(link: new_history.link)
      old_history = Deletehistory.find_by(link: new_history.link)
      old_history.destroy
    end
    new_history.save
    histories_stock_limit = 20
    histories = Deletehistory.all
    histories[0].destroy if histories.count > histories_stock_limit
  end
end

app/models/deletehistory.rb
class Deletehistory < ApplicationRecord
  validates :title, :link, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  has_many :connects, dependent: :destroy
  has_many :boxes, dependent: :destroy
  has_many :deletehistory, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['AUTH_USER'] && password == ENV['AUTH_PASSWORD']
    end
  end
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :move_to_session, only: %i[edit]
  before_action :set_box, only: %i[edit update destroy]

  def index
    @boxes = Box.includes(:user)
  end

  def create
    box = Box.create(name: params[:name], position: params[:position], user_id: current_user.id)
    render json: { box: box }
  end

  def edit
    move_to_root
  end

  def update
    if @box.update(box_params)
      redirect_to box_connects_path(@box)
    else
      render :edit
    end
  end

  def destroy
    connects = @box.connects
    @box.destroy_all_history
    if @box.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def box_params
    params.require(:box).permit(:name, :position).merge(user_id: current_user.id)
  end

  def set_box
    @box = Box.find(params[:id])
  end

  def move_to_session
    redirect_to new_user_session_path unless user_signed_in?
  end

  def move_to_root
    redirect_to root_path unless current_user.id == @box.user.id
  end
end

app/controllers/connects_controller.rb
class ConnectsController < ApplicationController
  before_action :move_to_session, only: %i[index]
  before_action :set_box, only: %i[index create destroy]

  def index
    @connect = Connect.new
    move_to_root
    @connects = @box.connects.includes(:user)
  end

  def create
    @connect = @box.connects.new(connect_params)
    if @connect.save
      redirect_to box_connects_path(@box)
    else
      @connects = @box.connects.includes(:user)
      render :index
    end
  end

  def destroy
    @connect = Connect.find(params[:id])
    @connect.delete_history
    if @connect.destroy
      redirect_to box_connects_path(@box)
    else
      render box_connects_path(@box)
    end
  end

  def destroy_all
    box = Box.find(params[:box_id])
    connects = box.connects
    destroy_all_history(connects)
    if connects.destroy_all
      redirect_to box_connects_path(box)
    else
      render edit_box_path(box)
    end
  end

  def search
    @search_connects = if params[:title].present?
                         current_user.connects.where('title LIKE ?', "%#{params[:title]}%")
                       else
                         current_user.connects.none
                       end
  end

  private

  def connect_params
    params.require(:connect).permit(:title, :link, :position).merge(user_id: current_user.id)
  end

  def move_to_session
    redirect_to new_user_session_path unless user_signed_in?
  end

  def move_to_root
    redirect_to root_path unless current_user.id == @box.user_id
  end

  def set_box
    @box = Box.find(params[:box_id])
  end

  def destroy_all_history(connects)
    connects.each(&:delete_history)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/helpers/connects_helper.rb
module ConnectsHelper
end

app/views/boxes/_logout.html.erb
<div class="first-visit">
  <div class="background-wrap">
    <header class="first-view-wrap">
      <h2 class="top-description">よく開くページを整理</h2>
      <p class="top-text">たくさんのタブで散らかっていませんか? 簡単なページ登録で、いつでも素早く開けます。</p>
      <button onclick="location.href='/users/sign_in'" class="first-view-sign">タブを整理</button>
    </header>
  </div>
  <div class="background-second">
    <div class="demo-view-wrap">
      <h2>グループで分ける</h2>
      <p>タブを用途別にグルーピングできます。たくさん保存しても、タイトル検索で素早く見つけます。</p>
      <%= image_tag 'demo_views.gif', class: "demo-view" %>
    </div>
  </div>
  <div class="background-third">
    <%= image_tag 'link(iPhone 6_7_8 Plus).png', class: "iphone-img" %>
    <%= image_tag 'link(iPad).png', class: "ipad-img" %>
  </div>
</div>

app/views/boxes/_side_bar.html.erb
<aside class="side-bar", id="side-bar">
  <% if user_signed_in? %>
    <% current_user.boxes.each do |box| %>
      <%= link_to box.name, box_connects_path(box), class: "box" %>
    <% end %>
  <% end %>

  <div id="box-lists">
  </div>

  <%= form_with url: boxes_path, id:"box-form", method: :post do |f| %>
    <%= f.text_field :name, class: "new-box-text", id: "box-text", placeholder: "10文字以内で入力", style: 'display:none', maxlength:"10", required: true %>
    <%= f.hidden_field :position, value: 1 %>
    <%= f.submit "追加", class: "box-submit", id: "box-submit-id", style: "display:none" %>
  <% end %>
  <% if user_signed_in? %>
    <div class="new-box box" id="new-box" display="block">＋ グループ作成</div>
  <% end %>
</aside>

app/views/boxes/edit.html.erb
<%= render "shared/single-header"%>
<%= form_with model: @box, class: "up-box-form", local: true do |f| %>
  <%= f.label :name, "名前変更", class:"up-box-text" %>
  <%= f.text_field :name, placeholder: "リスト名入力（20字以内）", class: "up-box", maxlength:"20"; %>
  <%= f.hidden_field :position, value: 1%>
  <%= f.submit "更新", class: "up-box-submit" %>
<% end %>
<div class = "box-delete"><%= link_to "全てのリンク削除", destroy_all_box_connects_path(@box.id), method: :delete, class: "box-delete-in", data: { confirm: "グループ内のリンクを削除しますか？"} %></div>
<div class = "box-delete"><%= link_to "グループを削除", box_path, method: :delete, class: "box-delete-in", data: { confirm: "グループを削除しますか？"} %></div>

app/views/boxes/index.html.erb
<%= render "shared/header" %>
<div class="wrapper">
    <% unless user_signed_in? %>
      <%= render "logout" %>
    <% else %>
      <%= render "side_bar"%>
    <% end %>
</div>

app/views/connects/_main_connect.html.erb
<main class="main-page">
  <header class="m-header">
    <% if user_signed_in? && current_user.id == @box.user.id %>
      <div class = "b-title"><%= @box.name %></div>
      <div class = "all-open", id = "all-open-id">すべて開く：<%= @box.connects.count %></div>
      <%= link_to "編集", edit_box_path(@box.id), class: "box-edit" %>
    <% end %>
  </header>

  <div class="connect-list">
    <% @box.connects.each do |connect| %>
      <div class="connect-container">
        <a class = "image-link" href= "<%= connect.link %>" target=_blank, rel="noopener noreferrer" ><img src="https://favicon.hatena.ne.jp/?url=<%= connect.link %>" class="image-set"></a>
        <%= link_to connect.title, connect.link, class: "link-title", target: :_blank, rel:"noopener noreferrer" %>
        <%= link_to "削除", box_connect_path(@box, connect.id), method: :delete, class: "con-delete" %>
      </div>
    <% end %>
  </div>

  <%= form_with model: [@box, @connect], class: "connect-form", id: "connect-form", local: true do |f| %>
    <%= f.text_field :title, class: "connect-title", id: "connect-title-id", placeholder: "タイトル", style: "display:none", maxlength:"20", required: true %>
    <%= f.url_field :link, class: "connect-link", id: "connect-link-id", placeholder: "URL", style: "display:none", required: true %>
    <%= f.submit "追加", class: "connect-submit", id: "connect-submit-id", style: "display:none" %>
    <%= f.hidden_field :position, value: 1 %>
  <% end %>
  <div class ="add-connect" id ="add-connect-id" style="display:block">+ リンク作成</div>
</main>

app/views/connects/index.html.erb
<%= render "shared/header" %>
<div class="wrapper">
  <%= render "boxes/side_bar" %>
  <%= render "main_connect" %>
</div>

app/views/connects/search.html.erb
<%= render "shared/header" %>
<h1 class="search-top-text">検索結果一覧 : <%= @search_connects.count %>件</h1>
<div class="connect-list">
  <% @search_connects.each do |connect| %>
    <div class="connect-container">
      <a class = "image-link" href= "<%= connect.link %>" target=_blank, rel="noopener noreferrer" ><img src="https://favicon.hatena.ne.jp/?url=<%= connect.link %>" class="image-set"></a>
      <%= link_to connect.title, connect.link, class: "link-title", target: :_blank, rel:"noopener noreferrer" %>
    </div>
  <% end %>
</div>
<% if @search_connects.count == 0 %>
  <p class="search-none">検索された文字列を含むリンクタイトルは存在しません。</p>
  <p class="search-all">登録済みのすべてのリンクを表示します。</p>
  <div class="connect-list">
    <% current_user.connects.each do |connect| %>
      <div class="connect-container">
        <a class = "image-link" href= "<%= connect.link %>" target=_blank, rel="noopener noreferrer" ><img src="https://favicon.hatena.ne.jp/?url=<%= connect.link %>" class="image-set"></a>
        <%= link_to connect.title, connect.link, class: "link-title", target: :_blank, rel:"noopener noreferrer" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>LinkBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <ul class="error-alert">
    <% model.errors.full_messages.each do |message| %>
      <li class="error-message"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<header class="top-page-header">
  <% if user_signed_in? %>
    <%= image_tag 'hamburger-menu.svg', class: "side-view nav", id: "side-view" %>
  <% end %>
  <%= link_to "Link", root_path, class: "nav title" %>
  <% if user_signed_in? %>
    <%= form_with url: search_box_connects_path(:box_id), method: :get, class: "search-form", local: true do |f| %>
        <%= f.text_field :title, placeholder: "タイトルを検索", required: true, class:"search-title" %>
        <%= f.submit "検索" %>
    <% end %>

    <div class="delete-recent">
        <%= image_tag 'trash.svg' ,class: "nav" %>
        <ul class="delete-history">
        <% current_user.deletehistory.each do |history| %>
        <div class="del-lists">
            <li><a class = "del-image-link" href= "<%= history.link %>" target=_blank, rel="noopener noreferrer" ><img src="https://favicon.hatena.ne.jp/?url=<%= history.link %>"></a></li>
            <li><%= link_to history.title, history.link, class: "del-link-title", target: :_blank, rel:"noopener noreferrer" %></li>
        </div>
        <% end %>
        </ul>
    </div>
    <%= link_to current_user.nickname, root_path, class: "nav user-nickname" %>
    <div class="user-menu-btn">
        <%= image_tag 'face.svg', class: "nav user-menu" %>
        <ul class="user-menu-lists", id="user-menu-lists">
        <li class="user-menu-list"><%= link_to current_user.nickname, root_path %></li>
        <li class="user-menu-list"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        </ul>
    </div>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav logout" %>
    <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "nav login" %>
        <%= link_to "新規登録", new_user_registration_path, class: "nav sign-up" %>
  <% end %>
</header>

app/views/shared/_single-header.html.erb
<header class="single-header"><%= link_to "Link", root_path, class: "single-header-title" %></header>